{
 "title": "Test task Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Requests by Status (Stub)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m])) by (status)",
     "legendFormat": "Status {{status}}"
    }
   ]
  },
  {
   "title": "Response Time (Script)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"avg\") AS \"Avg\",\n       mean(\"pct90.0\") AS \"p90\",\n       mean(\"pct95.0\") AS \"p95\",\n       mean(\"pct99.0\") AS \"p99\"\nFROM \"jmeter\"\nWHERE $timeFilter\nGROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Responses by Status (Script) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "SELECT sum(\"count\") \nFROM \"jmeter\" \nWHERE $timeFilter AND \"transaction\"='HTTP Request'\nGROUP BY time(1m), \"statut\""
    }
   ]
  }
 ]
}